// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4jQcaIpi7XWvn9YjOtXs7Gzk9ouVyl0E',
    appId: '1:350109597967:web:4b3545de98d13ed07dbe7a',
    messagingSenderId: '350109597967',
    projectId: 'doitnow-c26f9',
    authDomain: 'doitnow-c26f9.firebaseapp.com',
    storageBucket: 'doitnow-c26f9.firebasestorage.app',
    measurementId: 'G-MT93T320SY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqz_TB4MmgC05rfe9fdbD5IBu42LTKpkE',
    appId: '1:350109597967:ios:c166c02f64fc0a4a7dbe7a',
    messagingSenderId: '350109597967',
    projectId: 'doitnow-c26f9',
    storageBucket: 'doitnow-c26f9.firebasestorage.app',
    iosBundleId: 'com.example.doItNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4jQcaIpi7XWvn9YjOtXs7Gzk9ouVyl0E',
    appId: '1:350109597967:web:82dbfafef506ef5d7dbe7a',
    messagingSenderId: '350109597967',
    projectId: 'doitnow-c26f9',
    authDomain: 'doitnow-c26f9.firebaseapp.com',
    storageBucket: 'doitnow-c26f9.firebasestorage.app',
    measurementId: 'G-R5YF56CKLQ',
  );
}
